version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    container_name: kanban-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: kanban
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  db-test:
    image: postgres:15
    restart: always
    container_name: kanban-db-test
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: kanban
    ports:
      - "5434:5432"  # Porta do host agora é 5433 para evitar conflito
    volumes:
      - pgdata-test:/var/lib/postgresql/data  # Volume separado para evitar conflitos de dados

volumes:
  pgdata:
  pgdata-test:
